sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t egorovma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true egorovma/react-test npm test

after_success:
  - docker build -t egorovma/multi-client ./client
  - docker build -t egorovma/multi-nginx ./nginx
  - docker build -t egorovma/multi-server ./server
  - docker build -t egorovma/multi-worker ./worker
  # Login in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -username "$DOCKER_ID" --password-stdin
  # push to Docker hub
  - docker push egorovma/multi-client
  - docker push egorovma/multi-nginx
  - docker push egorovma/multi-server
  - docker push egorovma/multi-worker
